package tenancy

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
)

// ErrSAMLLoginCodeNotFound covers a missing, already-consumed, or expired
// code -- indistinguishable to the caller deliberately.
var ErrSAMLLoginCodeNotFound = errors.New("saml login code not found")

// CreateSAMLLoginCode persists a short-lived, single-use login code. code
// must already be a cryptographically random token generated by the caller
// (e.g. controllers' randomToken()) -- this method only stores it.
func (c *ControlPlane) CreateSAMLLoginCode(ctx context.Context, code, identityID, tenantID string, ttl time.Duration) error {
	if _, err := c.pool.Exec(ctx,
		`INSERT INTO saml_login_codes (code, identity_id, tenant_id, expires_at) VALUES ($1, $2, $3, $4)`,
		code, identityID, tenantID, time.Now().Add(ttl)); err != nil {
		return fmt.Errorf("create saml login code: %w", err)
	}
	return nil
}

// ConsumeSAMLLoginCode validates and deletes a login code atomically
// (DELETE ... RETURNING), returning the identity/tenant it was issued for.
// Returns ErrSAMLLoginCodeNotFound if the code doesn't exist, was already
// consumed by a prior call, or has expired.
func (c *ControlPlane) ConsumeSAMLLoginCode(ctx context.Context, code string) (identityID, tenantID string, err error) {
	err = c.pool.QueryRow(ctx,
		`DELETE FROM saml_login_codes WHERE code = $1 AND expires_at > NOW() RETURNING identity_id, tenant_id`,
		code,
	).Scan(&identityID, &tenantID)
	if errors.Is(err, pgx.ErrNoRows) {
		return "", "", ErrSAMLLoginCodeNotFound
	}
	if err != nil {
		return "", "", fmt.Errorf("consume saml login code: %w", err)
	}
	return identityID, tenantID, nil
}
